server:
  port: 9004
spring: 
  application:  
    name: ktc-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.132:3307/ktc_article?characterEncoding=UTF8
    username: root
    password: admin
  jpa:
    properties:
      hibernate:
        format_sql: true	# 格式化sql
        show_sql: true		# 显示sql
  redis:
    host: 192.168.25.132
    port: 6379
